teacher:
  name: dinov2_vits14
  checkpoint: ""

student:
  name: dinov2_vits14
  checkpoint: ""
  r: 24

hyperparameters:
  lr: 7.50E-04
  min_lr: 1.0e-6
  warmup_lr_scale: 1.0e-4
  warmup_epochs: 1
  batch_size: 1024
  num_workers: 32
  epochs: 5
  mixup_alpha: 1.0 
  mixup_classes: 10450
  accumulations: 2
  in_memory: False
  gradient_clip_val: 1.5


args:
  device: cuda:0
  data_dir: ""
  cache_path: ""
  precision: "bf16-mixed"