dinov2:
  name: dinov2_vits14
  checkpoint: ""

tome:
  name: dinov2_vits14
  checkpoint: ""
  r: 24

head:
  num_classes: 1000
  checkpoint: ""

hyperparameters:
  lr: 1.0E-04
  min_lr: 1.0e-7
  warmup_lr_scale: 1.0e-6
  warmup_epochs: 1
  batch_size: 256
  test_batch_size: 32
  num_workers: 16
  epochs: 100
  mixup_alpha: 0.8
  accumulations: 1
  in_memory: False
  gradient_clip_val: 2.5

args:
  device: cuda:0
  data_dir: ""
  precision: "bf16-mixed"