dinov2_vittiny14:
  img_size: 518
  patch_size: 14
  embed_dim: 192
  depth: 12
  num_heads: 3
  mlp_ratio: 4
  init_values: 1.0 
  ffn_layer: 'mlp' 
  block_chunks: 0 
  num_register_tokens: 0 
  interpolate_antialias: False 
  interpolate_offset: 0.1

dinov2_vits14:
  img_size: 518
  patch_size: 14
  embed_dim: 384
  depth: 12
  num_heads: 6
  mlp_ratio: 4
  init_values: 1.0 
  ffn_layer: 'mlp' 
  block_chunks: 0 
  num_register_tokens: 0 
  interpolate_antialias: False 
  interpolate_offset: 0.1

dinov2_vitb14:
  img_size: 518
  patch_size: 14
  embed_dim: 768
  depth: 12
  num_heads: 12
  mlp_ratio: 4
  init_values: 1.0 
  ffn_layer: 'mlp' 
  block_chunks: 0 
  num_register_tokens: 0 
  interpolate_antialias: False 
  interpolate_offset: 0.1

dinov2_vitl14:
  img_size: 518
  patch_size: 14
  embed_dim: 1024
  depth: 24
  num_heads: 16
  mlp_ratio: 4
  init_values: 1.0 
  ffn_layer: 'mlp' 
  block_chunks: 0 
  num_register_tokens: 0 
  interpolate_antialias: False 
  interpolate_offset: 0.1

dinov2_vitg14:
  img_size: 518
  patch_size: 14
  embed_dim: 1536
  depth: 40
  num_heads: 24
  mlp_ratio: 4
  init_values: 1.0 
  ffn_layer: 'swiglufused' 
  block_chunks: 0 
  num_register_tokens: 0 
  interpolate_antialias: False 
  interpolate_offset: 0.1